language: python

python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hostapd dnsmasq

install:
  - pip install pylint
  - python setup.py install

script:
  - pylint --errors-only wifiphisher
